export const PIXEL_ICONS = {
  estrela: '★',
  forca: '♦',
  alvo: '◉',
  raio: '⚡',
  foguete: '▲',
  lampada: '◐',
  arte: '◈',
  corrida: '►',
  livro: '■',
  musica: '♫',
  comida: '●',
  sono: '◢',
  agua: '◇',
  meditacao: '◎',
  yoga: '⊕',
  academia: '╬',
  estudo: '▣',
  codigo: '◘',
  trabalho: '▧',
  familia: '♥',
  amigos: '◆',
  dinheiro: '◙',
  saude: '+',
  limpeza: '▓',
};

export const PIXEL_ICON_NAMES = {
  '★': 'ESTRELA',
  '♦': 'FORÇA',
  '◉': 'ALVO',
  '⚡': 'RAIO',
  '▲': 'FOGUETE',
  '◐': 'LÂMPADA',
  '◈': 'ARTE',
  '►': 'CORRIDA',
  '■': 'LIVRO',
  '♫': 'MÚSICA',
  '●': 'COMIDA',
  '◢': 'SONO',
  '◇': 'ÁGUA',
  '◎': 'MEDITAÇÃO',
  '⊕': 'YOGA',
  '╬': 'ACADEMIA',
  '▣': 'ESTUDO',
  '◘': 'CÓDIGO',
  '▧': 'TRABALHO',
  '♥': 'FAMÍLIA',
  '◆': 'AMIGOS',
  '◙': 'DINHEIRO',
  '+': 'SAÚDE',
  '▓': 'LIMPEZA',
};

export const PIXEL_ICON_LIST = Object.values(PIXEL_ICONS);
